### ISSUE TITLE
footer links and text

### ISSUE THREAD

**Issue by Maxhodges** [white-rabbit-japan/wreHomePage#10]
simplify footer and link to real things

**Comment by SabinaFischer** [comment]
![footer_links](https://cloud.githubusercontent.com/assets/13582674/9001235/c03d8b96-378f-11e5-83ca-c64d9ab510d4.png)

Possible options for the footer. This is the combination of a Site Map (1st column) with our current footer. Removed Forums and added a link to the Product Blog instead so it is still linked somewhere. 

I think the most important column is "Community" as it has the Help Desk but we really could simplify things even more if we wanted. Such as just having one thing per column such as "Help Desk", " T&C" and "Privacy Policy". Depends how slim we want things!

**Comment by Maxhodges** [comment]
I wonder if maybe the MY WRE site column is not necessary . . . since they might not be logged in. and it's in the big menu anyway

but the other stuff is looking good. I can drop that in. might use some fonts for twitter facebook too
