### ISSUE TITLE
Need screenshots for All the features you need section

### ISSUE THREAD

**Issue by Maxhodges** [white-rabbit-japan/wreHomePage#4]
create screenshots from app the each feature in this section

**Comment by SabinaFischer** [comment]
![wre_cart](https://cloud.githubusercontent.com/assets/13582674/9003260/7c2e798e-37a7-11e5-90da-8ebf4f1fb67c.png)
![wre_cart_nav](https://cloud.githubusercontent.com/assets/13582674/9003259/7c2866fc-37a7-11e5-99ab-a9a4cb021c37.png)
![wre_cart_nav_v2](https://cloud.githubusercontent.com/assets/13582674/9003261/7c4bb6ca-37a7-11e5-9d2b-849076cf7776.png)
![wre_cart2](https://cloud.githubusercontent.com/assets/13582674/9003262/7c4f3dd6-37a7-11e5-9e45-46eaf92f7656.png)
![wre_cart2_nav](https://cloud.githubusercontent.com/assets/13582674/9003264/7c6380fc-37a7-11e5-9034-199e37acf4c5.png)
![wre_checkout](https://cloud.githubusercontent.com/assets/13582674/9003263/7c5fdec0-37a7-11e5-9a70-26f0d2869f02.png)
![wre_consolidate](https://cloud.githubusercontent.com/assets/13582674/9003265/7c684a7e-37a7-11e5-9a95-4420949e43f1.png)
![wre_consolidaterequest](https://cloud.githubusercontent.com/assets/13582674/9003266/7c68b87e-37a7-11e5-8803-55aacf279a95.png)
![wre_consolidaterequest2](https://cloud.githubusercontent.com/assets/13582674/9003267/7c6e13be-37a7-11e5-8e47-a086567e6416.png)
![wre_dashboard](https://cloud.githubusercontent.com/assets/13582674/9003268/7c727c4c-37a7-11e5-8360-f5fce1b28e1d.png)
![wre_mailbox](https://cloud.githubusercontent.com/assets/13582674/9003269/7c7ed3fc-37a7-11e5-8418-69bea398f821.png)
![wre_orderdetail](https://cloud.githubusercontent.com/assets/13582674/9003270/7c840502-37a7-11e5-8367-22e56391c911.png)
![wre_orderstatus](https://cloud.githubusercontent.com/assets/13582674/9003272/7c8c1a12-37a7-11e5-9fe5-d865ca049ba3.png)
![wre_orderstatus_multiplestatus](https://cloud.githubusercontent.com/assets/13582674/9003271/7c89f8fe-37a7-11e5-95ae-40150fad1fe2.png)

**Comment by SabinaFischer** [comment]
I tried to cover consolidation as well, shipping was broken when taking screenshots so I couldn't do the full process.

Oh and I made the aspect ratio a little square to make it all fit better for the site rather than being really wide.
